sudo: false
language: java
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   script: xvfb-run mvn verify -B
 - os: osx
   osx_image: xcode8.2
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
   before_install:
    - export JAVA_HOME=$(/usr/libexec/java_home)
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
   - $HOME/.cache/pip
install:
 - virtualenv env
 - . env/bin/activate
 - pip install pandas
 - mvn package -B
after_success:
 - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

